<a href="https://colab.research.google.com/github/BumjuneKim/hymot-python/blob/main/week11/week11_assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

a = np.array([[1, 2, 3], [4, 5, 6]])
a.shape

(2, 3)

In [10]:
a = np.array([1, 2, 3, 4, 5, 6])
a

a[0]
a[0] = 10

a

b = a[3:]
b
b[0] = 40
b
a

array([10,  2,  3, 40,  5,  6])

In [19]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a
a[1, 3]

print(a.ndim)
print(a.shape)
print(len(a.shape))
print(len(a.shape) == a.ndim)
print(a.size)

import math

print(a.size == math.prod(a.shape))
print(a.dtype)



2
(3, 4)
2
True
12
True
int64


In [30]:
print(np.zeros(2))
print(np.ones(2))
print(np.empty(2))
print(np.arange(4))
print(np.arange(2, 9, 2))
print(np.linspace(0, 10, num=5))
x = np.ones(2, dtype=np.int64)
print(x)

[0. 0.]
[1. 1.]
[1. 1.]
[0 1 2 3]
[2 4 6 8]
[ 0.   2.5  5.   7.5 10. ]
[1 1]


In [31]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
print(np.sort(arr))

[1 2 3 4 5 6 7 8]


In [33]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
print(np.concatenate((a, b)))


x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])

print(np.concatenate((x, y), axis=0))

[1 2 3 4 5 6 7 8]
[[1 2]
 [3 4]
 [5 6]]


In [34]:
array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0 ,1 ,2, 3],
                           [4, 5, 6, 7]]])

print(array_example.ndim)
print(array_example.size)
print(array_example.shape)

3
24
(3, 2, 4)


In [42]:
a = np.arange(6)
print(a)

b = a.reshape(3, 2)
print(b)

np.reshape(a, (1, 6), 'C')

[0 1 2 3 4 5]
[[0 1]
 [2 3]
 [4 5]]


array([[0, 1, 2, 3, 4, 5]])

In [48]:
a = np.array([1, 2, 3, 4, 5, 6])
print(a.shape)

a2 = a[np.newaxis, :]
print(a2.shape)

row_vector = a[np.newaxis, :]
row_vector.shape

col_vector = a[:, np.newaxis]
col_vector.shape

(6,)
(1, 6)


(6, 1)

In [50]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

b = np.expand_dims(a, axis=1)
b.shape

c = np.expand_dims(a, axis=0)
c.shape

(1, 6)

In [61]:
data = np.array([1, 2, 3])

print(data[1])
print(data[0:2])
print(data[1:])
print(data[-2:])
print(data[-3])

a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a[a < 5])

five_up = (a >= 5)
print(a[five_up])

divisible_by_2 = a[a%2==0]
print(divisible_by_2)

c = a[(a > 2) & (a < 11)]
print(c)

five_up = (a > 5) | (a == 5)
print(five_up)

2
[1 2]
[2 3]
[2 3]
1
[1 2 3 4]
[ 5  6  7  8  9 10 11 12]
[ 2  4  6  8 10 12]
[ 3  4  5  6  7  8  9 10]
[[False False False False]
 [ True  True  True  True]
 [ True  True  True  True]]


In [65]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
b = np.nonzero(a < 5)
print(b)

list_of_coordinates= list(zip(b[0], b[1]))

for coord in list_of_coordinates:
    print(coord)

print(a[b])

not_there = np.nonzero(a == 42)
print(not_there)

(array([0, 0, 0, 0]), array([0, 1, 2, 3]))
(np.int64(0), np.int64(0))
(np.int64(0), np.int64(1))
(np.int64(0), np.int64(2))
(np.int64(0), np.int64(3))
[1 2 3 4]
(array([], dtype=int64), array([], dtype=int64))


In [10]:
a = np.array([1,  2,  3,  4,  5,  6,  7,  8,  9, 10])
arr1 = a[3:8]
print(arr1)

a1 = np.array([[1, 1],
               [2, 2]])

a2 = np.array([[3, 3],
               [4, 4]])

np.vstack((a1, a2))
np.hstack((a1, a2))

x = np.arange(1, 25).reshape(2, 12)
print(x)

np.hsplit(x, 3)
np.hsplit(x, (3, 4))

[4 5 6 7 8]
[[ 1  2  3  4  5  6  7  8  9 10 11 12]
 [13 14 15 16 17 18 19 20 21 22 23 24]]


[array([[ 1,  2,  3],
        [13, 14, 15]]),
 array([[ 4],
        [16]]),
 array([[ 5,  6,  7,  8,  9, 10, 11, 12],
        [17, 18, 19, 20, 21, 22, 23, 24]])]

In [14]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

b1 = a[0, :]
print(b1)

b1[0] = 99
print(b1)
print(a)

b2 = a.copy()
print(b2)

[1 2 3 4]
[99  2  3  4]
[[99  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[99  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [20]:
data = np.array([1, 2])
ones = np.ones(2, dtype=int)
data + ones

print(data - ones)
print(data * data)
print(data / data)

a = np.array([1, 2, 3, 4])

a.sum()

b = np.array([[1, 1], [2, 2]])
print(b.sum(axis=0))
print(b.sum(axis=1))

[0 1]
[1 4]
[1. 1.]
[3 3]
[2 4]


In [25]:
data = np.array([1.0, 2.0])
data * 1.6

print(data.max())
print(data.min())
print(data.sum())

a = np.array([[0.45053314, 0.17296777, 0.34376245, 0.5510652],
              [0.54627315, 0.05093587, 0.40067661, 0.55645993],
              [0.12697628, 0.82485143, 0.26590556, 0.56917101]])
print(a.sum())
print(a.min())

a.min(axis=0)

2.0
1.0
3.0
4.8595784
0.05093587


array([0.12697628, 0.05093587, 0.26590556, 0.5510652 ])

In [39]:
data = np.array([[1, 2], [3, 4], [5, 6]])
print(data)

print(data[0, 1])
print(data[1:3])
print(data[0:2, 0])

print(data.max())
print(data.min())
print(data.sum())

data = np.array([[1, 2], [5, 3], [4, 6]])
print(data)
print(data.max(axis=0))
print(data.max(axis=1))

data = np.array([[1, 2], [3, 4]])
ones = np.array([[1, 1], [1, 1]])
print(data + ones)

data = np.array([[1, 2], [3, 4], [5, 6]])
ones_row = np.array([[1, 1]])
print(data + ones_row)

np.ones((4, 3, 2))

np.ones(3)
np.zeros(3)
rng = np.random.default_rng()
rng.random(3)

np.ones((3, 2))
np.zeros((3, 2))
rng.random((3, 2))

[[1 2]
 [3 4]
 [5 6]]
2
[[3 4]
 [5 6]]
[1 3]
6
1
21
[[1 2]
 [5 3]
 [4 6]]
[5 6]
[2 5 6]
[[2 3]
 [4 5]]
[[2 3]
 [4 5]
 [6 7]]


array([[0.97193144, 0.81669762],
       [0.87432415, 0.45374526],
       [0.2211842 , 0.06326239]])

In [41]:
rng.integers(5, size=(2, 4))

array([[0, 3, 3, 4],
       [4, 3, 0, 0]])

In [47]:
a = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])

unique_values = np.unique(a)
print(unique_values)

unique_values, indices_list = np.unique(a, return_index=True)
print(indices_list)

unique_values, occurrence_count = np.unique(a, return_counts=True)
print(occurrence_count)

a_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [1, 2, 3, 4]])
unique_values = np.unique(a_2d)
print(unique_values)

unique_rows = np.unique(a_2d, axis=0)
print(unique_rows)

unique_rows, indices, occurrence_count = np.unique(
     a_2d, axis=0, return_counts=True, return_index=True)
print(unique_rows)
print(indices)
print(occurrence_count)

[11 12 13 14 15 16 17 18 19 20]
[ 0  2  3  4  5  6  7 12 13 14]
[3 2 2 2 1 1 1 1 1 1]
[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[0 1 2]
[2 1 1]


In [51]:
print(data.reshape(2, 3))
print(data.reshape(3, 2))

arr = np.arange(6).reshape((2, 3))
print(arr)

print(arr.transpose())
print(arr.T)

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]
[[0 1 2]
 [3 4 5]]
[[0 3]
 [1 4]
 [2 5]]
[[0 3]
 [1 4]
 [2 5]]


In [58]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
reversed_arr = np.flip(arr)
print('Reversed Array: ', reversed_arr)


arr_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
reversed_arr = np.flip(arr_2d)
print(reversed_arr)

reversed_arr_rows = np.flip(arr_2d, axis=0)
print(reversed_arr_rows)

reversed_arr_columns = np.flip(arr_2d, axis=1)
print(reversed_arr_columns)

arr_2d[1] = np.flip(arr_2d[1])
print(arr_2d)

arr_2d[:,1] = np.flip(arr_2d[:,1])
print(arr_2d)

Reversed Array:  [8 7 6 5 4 3 2 1]
[[12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]
[[ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]
[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]]
[[ 1  2  3  4]
 [ 8  7  6  5]
 [ 9 10 11 12]]
[[ 1 10  3  4]
 [ 8  7  6  5]
 [ 9  2 11 12]]


In [60]:
x = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
x.flatten()

a1 = x.flatten()
a1[0] = 99
print(x)  # Original array
print(a1)  # New array

a2 = x.ravel()
a2[0] = 98
print(x)  # Original array
print(a2)  # New array

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[99  2  3  4  5  6  7  8  9 10 11 12]
[[98  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[98  2  3  4  5  6  7  8  9 10 11 12]
